### ISSUE TITLE
Variables defined twice

### ISSUE THREAD

**Issue by mvisonneau** [gds-operations/puppet-resolvconf#11]
I have a problem with the usage of the module :

Each of my entries are defined twice

```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 172.16.6.11
nameserver 172.16.6.12
nameserver 172.16.6.11
nameserver 172.16.6.12
search example.lan
search example.lan
```

Here is my hiera config : 

```yaml
resolvconf::nameservers:
  - 172.16.6.11
  - 172.16.6.12
resolvconf::search:
  - example.lan
```

**Comment by alexmuller** [comment]
Hi @mvisonneau,

I've tried to reproduce this with the latest version on the Puppet Forge (0.3.2) and the latest master and I'm unable to replicate the error you're experiencing or see anything that would cause it.

Are you still seeing this issue? If so, do you have any other details that would help us diagnose it?

**Comment by mvisonneau** [comment]
Hi @alexmuller,

Indeed, I figured out this problem later. It was not related to the module but on a previous module I used for managing resolvconf that did not really cleaned up the configuration files.

Thanks
