### ISSUE TITLE
Debian jessie

### ISSUE THREAD

**Issue by hoene** [gds-operations/puppet-resolvconf#19]
On debian jessie, I get the message

Notice: /Stage[main]/Resolvconf::Config/File[/etc/resolv.conf]/target: target changed '/etc/resolvconf/run/resolv.conf' to '../run/resolvconf/resolv.conf'

everytime. Actually, both ways link to the same file...

**Comment by choene** [comment]
easy... just change in config.pp 


  $resolv_conf_target = $::lsbmajdistrelease ? {
    /^1[0-1]/ => '/etc/resolvconf/run/resolv.conf',
    /^8/ => '/etc/resolvconf/run/resolv.conf',
    default     => '../run/resolvconf/resolv.conf',
  }

**Comment by rjw1** [comment]
HI, @choene could you provide a pull request to fix this?

**Comment by j-vizcaino** [comment]
It seems support for Debian is already OK in the current master branch but for some unknown reason, the 0.3.3 release does not include the proper `case $::operatingsystem` block.
@rjw1 Is it possible to release the master branch as a 0.3.4 in order to fix this please?

**Comment by deanwilson** [comment]
Closing this issue due to age.
