### ISSUE TITLE
Gemfile.lock

### ISSUE THREAD

**Issue by arioch** [gds-operations/puppet-resolvconf#22]
... is out of date. Hence breaking CI builds.
Why is it even in the repository?

Gems listed in Gemfile are out of date too... would you accept patches for this?

**Comment by rjw1** [comment]
Hi @arioch,
We remove it in our travis builds.
Yes we would accept PRs to bump stuff in the Gemfile.

**Comment by deanwilson** [comment]
We've updated most of this in #28. Thank you for raising the issue, it's appreciated.
